import streamlit as st

def render_guide():
    st.markdown("### Phase, grade & heat-treatment guide")
    st.caption("A compact learning layer: what the terms mean, what QuenchIQ calculates, and where it deliberately stops.")
    items=[
        ("Austenite (γ)","The high-temperature FCC phase from which cooling transformation is screened. QuenchIQ assumes an appropriate austenitized condition; dissolution, homogenization, prior processing and grain growth are not simulated."),
        ("Steel grade library","QuenchIQ now includes representative screening chemistries for AISI 1045, 1080, 4140, 4340, 52100 and 8620 plus a custom chemistry option. These are representative values, not certified heat-analysis data."),
        ("Alloying elements","Mn, Ni, Cr and Mo now influence the alloy-sensitive Ms estimates. Additional elements are stored in the chemistry model for future grade-specific relationships. This does not yet create experimental CCT/TTT behavior."),
        ("Ferrite / Pearlite / Bainite","These transformation products are still allocated by a simplified screening model. Real start/finish temperatures, fractions, morphology and kinetics depend strongly on grade, austenite condition and cooling history."),
        ("Martensite","A diffusionless product formed as austenite cools below Ms. QuenchIQ uses alloy-sensitive empirical Ms estimates followed by a simplified cooling-path screening factor."),
        ("Ms and Mf*","Ms is the martensite-start temperature. QuenchIQ displays Andrews and Barbier-style empirical estimates separately and shows their blended value. Mf* remains a screening marker, not an exact measured endpoint."),
        ("Andrews Ms model","The QuenchIQ implementation uses an alloy-sensitive empirical form: Ms = 539 − 423C − 30.4Mn − 17.7Ni − 12.1Cr − 7.5Mo, with composition in wt%. It is an empirical screening relationship, not a universal law."),
        ("Barbier-style Ms model","A second alloy-sensitive empirical relationship is shown to expose model spread. Agreement between two equations should not be interpreted as experimental validation."),
        ("Ac1 / Ac3 / Acm","A1 is the eutectoid critical temperature. Ac3 is the upper critical boundary for hypoeutectoid steel and Acm is the corresponding hypereutectoid screening boundary. These remain simplified Fe–C relationships rather than grade-specific dilatometry."),
        ("Fe–Fe₃C vs TTT vs CCT","The Fe–Fe₃C diagram describes equilibrium phase relationships. TTT describes isothermal transformation. CCT describes continuous cooling. QuenchIQ's transformation map is still schematic, not an experimental CCT diagram."),
        ("Cooling condition","Brine, water, oil, air and furnace conditions differ in heat-transfer severity, but a medium name does not uniquely determine a cooling curve. Geometry, section thickness, agitation and quenchant temperature still matter."),
        ("Tempering","Tempering changes structure and properties of quenched steel. QuenchIQ currently represents it as a simplified property trend; carbide precipitation, detailed kinetics and grade-specific tempering curves are not modeled."),
    ]
    for title,body in items:
        with st.expander(title): st.write(body)
    st.markdown("### What QuenchIQ can do")
    st.markdown("""- Select a representative steel grade or edit its screening chemistry.\n- Compare alloy-sensitive Ms estimates using two empirical relationships.\n- Explore Ac1/Ac3/Acm screening boundaries, estimated Ms and a nominal Mf* marker.\n- Visualize a selected cooling path against a schematic transformation map.\n- Compare saved runs and inspect how chemistry and process changes alter screening outputs.\n- Use the Jominy-style explorer as a conceptual hardenability learning aid.""")
    st.markdown("### Model boundaries")
    st.markdown("""<div class="limit-card"><b>QuenchIQ is an educational screening model — not a production heat-treatment calculator.</b><br><br><b>Now supported:</b><br>• representative grade chemistry<br>• editable C, Mn, Si, Cr, Ni, Mo, V, Cu, W, Co, Al, P and S fields<br>• alloy-sensitive Ms screening<br><br><b>Still not modeled as validated engineering data:</b><br>• experimental grade-specific TTT/CCT curves or measured transformation kinetics<br>• real component cooling curves or heat-transfer coefficients<br>• section size, geometry, agitation or quenchant-temperature effects<br>• prior-austenite grain size and detailed austenitizing history<br>• detailed retained-austenite evolution<br>• detailed bainite, pearlite or carbide morphology/kinetics<br>• experimentally measured hardness, yield strength or tensile strength<br>• detailed tempering reactions and carbide precipitation</div>""",unsafe_allow_html=True)
    st.markdown("### Why real engineering data matters")
    st.info("For an engineering heat-treatment decision, use the actual heat chemistry, validated grade-specific TTT/CCT data, process records and laboratory measurements. Useful validation methods include dilatometry, hardness testing and metallography; tensile testing may be required when strength properties are specified.")
    st.markdown("### References & model basis")
    st.markdown("""**Koistinen–Marburger:** used for the temperature-driven martensite estimate below Ms.\n\n**Andrews-type Ms:** alloy-sensitive empirical relationship used for screening.\n\n**Barbier-style Ms:** second empirical estimate used to expose model spread.\n\n**Fe–C phase relationships:** used for approximate A1, Ac3 and Acm screening boundaries.\n\n**TTT/CCT:** used only as conceptual context; QuenchIQ does not yet plot published experimental transformation datasets.\n\n**Model status:** grade chemistry and Ms/Mf screening are now more realistic, but transformation kinetics, cooling physics and mechanical properties remain educational approximations.""")
